# Render Blueprint for Astro AI Companion
services:
  - type: web
    name: astro-ai-companion
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -c "from src.config.database import init_database; init_database()"
    startCommand: python src/web/app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: astro-ai-db
          property: connectionString
      - key: OPENROUTER_API_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production

  - type: worker
    name: astro-telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -c "
      import os;
      from src.telegram_bot.family_bot import FamilyTelegramBot;
      bot = FamilyTelegramBot(os.environ['TELEGRAM_BOT_TOKEN']);
      bot.run()
      "
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: astro-ai-db
          property: connectionString
      - key: OPENROUTER_API_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false

databases:
  - name: astro-ai-db
    databaseName: astro_ai_companion
    user: astro_user