# Enhanced Lal Kitab Rules and Remedies
# Comprehensive Lal Kitab system for professional-grade analysis

planetary_debts:
  pitru_rin:
    planets: [sun, jupiter, mars]
    indicators:
      - "Continuous health issues despite treatment"
      - "Obstacles in career progress" 
      - "Family disputes and disharmony"
      - "Financial instability"
    remedies:
      - "Serve father or elderly men daily"
      - "Donate wheat and jaggery on Sundays"
      - "Plant and care for trees"
      - "Feed cows regularly"
    
  matru_rin:
    planets: [moon, venus]
    indicators:
      - "Mental stress and anxiety"
      - "Problems with mother or maternal side"
      - "Issues in married life"
      - "Emotional instability"
    remedies:
      - "Serve mother and respect women"
      - "Donate white items on Mondays"
      - "Keep silver items in home"
      - "Worship Moon on full moon days"
      
  guru_rin:
    planets: [jupiter, mercury]
    indicators:
      - "Lack of wisdom in decisions"
      - "Educational obstacles"
      - "Disrespect towards teachers/elders"
      - "Spiritual emptiness"
    remedies:
      - "Respect teachers and learned people"
      - "Donate yellow items on Thursdays"
      - "Study religious texts"
      - "Help students in education"

unique_lal_kitab_remedies:
  mars_remedies:
    mars_in_1st: 
      - "Keep a piece of silver under the pillow"
      - "Donate red cloth to temple"
      - "Avoid wearing red on Tuesdays"
    mars_in_4th:
      - "Bury copper coin in house foundation"  
      - "Keep elephant statue in southwest"
      - "Don't keep weapons in home"
    mars_in_7th:
      - "Spouse should wear gold ornaments"
      - "Keep saunf (fennel) in red cloth"
      - "Perform Manglik remedies before marriage"
    mars_in_8th:
      - "Keep 8 almonds in red cloth under pillow"
      - "Donate blood or help blood donation"
      - "Avoid underground activities"
    mars_in_12th:
      - "Sleep with head towards south"
      - "Keep red handkerchief in pocket"
      - "Donate sports equipment"

  saturn_remedies:
    saturn_malefic:
      - "Donate mustard oil on Saturdays"
      - "Serve elderly and disabled people"
      - "Feed black cow or buffalo"
      - "Keep iron piece in pocket"
    saturn_in_7th:
      - "Donate black clothes to poor"
      - "Plant neem tree"
      - "Avoid wearing black on Saturdays"
    saturn_in_10th:
      - "Respect subordinates and servants"
      - "Donate shoes to needy"
      - "Keep coal piece in blue cloth"

  rahu_ketu_remedies:
    rahu_malefic:
      - "Keep Gomti Chakra in wallet"
      - "Donate radish and coconut"
      - "Wear silver on body"
      - "Avoid underground business"
    ketu_malefic:
      - "Donate multicolored cloth"
      - "Keep dog or feed stray dogs"
      - "Worship Lord Ganesha"
      - "Use camphor in home regularly"

lal_kitab_combinations:
  upachaya_houses: [3, 6, 10, 11]  # Houses where malefics give good results
  
  special_combinations:
    sun_mars_same_house:
      effect: "Aggressive nature, leadership qualities"
      remedy: "Donate copper and wheat on Sundays"
    
    moon_mars_opposition:
      effect: "Mental tension, blood pressure issues"
      remedy: "Keep silver bowl with water under bed"
      
    saturn_mars_conjunction:
      effect: "Accidents, disputes, legal issues"
      remedy: "Hang iron horseshoe at main door"
      
    jupiter_debilitated:
      effect: "Loss of wisdom, bad decisions"
      remedy: "Donate turmeric and gram dal on Thursdays"

house_specific_remedies:
  house_1:
    malefic_planets: "Health issues, personality problems"
    remedies: ["Keep photo of deity at entrance", "Wear gemstone for ascendant lord"]
    
  house_2:
    malefic_planets: "Financial problems, speech issues"
    remedies: ["Keep silver coins in safe", "Donate food grains"]
    
  house_4:
    malefic_planets: "Property disputes, mother's health"
    remedies: ["Keep Vastu items in home", "Plant tulsi in house"]
    
  house_7:
    malefic_planets: "Marriage problems, partnership issues"
    remedies: ["Keep pair items in home", "Worship together as couple"]
    
  house_8:
    malefic_planets: "Sudden losses, accidents, chronic illness"
    remedies: ["Keep Hanuman Chalisa at home", "Light mustard oil lamp"]
    
  house_10:
    malefic_planets: "Career obstacles, bad reputation"
    remedies: ["Respect elders at workplace", "Donate to charity regularly"]

timing_based_remedies:
  daily_remedies:
    morning: "Light lamp and incense"
    afternoon: "Feed animals or birds"
    evening: "Read spiritual texts"
    night: "Keep glass of water near bed"
    
  weekly_remedies:
    sunday: "Donate wheat and gud (jaggery)"
    monday: "Offer milk to Shiva"
    tuesday: "Feed red gram to birds"
    wednesday: "Donate green items"
    thursday: "Offer banana to Jupiter"
    friday: "Donate white flowers"
    saturday: "Give oil or iron items"

monthly_remedies:
  new_moon: "Start new spiritual practices"
  full_moon: "Perform charity and donations"
  ekadashi: "Fast and spiritual meditation"
  
gemstone_substitutes:
  ruby_substitute: ["red coral", "garnet", "red spinel"]
  pearl_substitute: ["moonstone", "white coral"]
  emerald_substitute: ["green tourmaline", "peridot"]
  diamond_substitute: ["white sapphire", "zircon"]
  yellow_sapphire_substitute: ["topaz", "citrine"]
  blue_sapphire_substitute: ["amethyst", "iolite"]
