
planets:
  sun:
    name: "Sun"
    sanskrit: "Surya"
    element: "fire"
    nature: "malefic"
    exaltation: "aries"
    debilitation: "libra"
    own_signs: ["leo"]
    friendly_signs: ["aries", "scorpio", "sagittarius", "pisces"]
    enemy_signs: ["gemini", "virgo", "aquarius"]
    
  moon:
    name: "Moon"
    sanskrit: "Chandra"
    element: "water"
    nature: "benefic"
    exaltation: "taurus"
    debilitation: "scorpio"
    own_signs: ["cancer"]
    friendly_signs: ["taurus", "gemini", "virgo", "libra", "capricorn", "aquarius"]
    enemy_signs: ["none"]
    
  mars:
    name: "Mars"
    sanskrit: "Mangal"
    element: "fire"
    nature: "malefic"
    exaltation: "capricorn"
    debilitation: "cancer"
    own_signs: ["aries", "scorpio"]
    friendly_signs: ["leo", "sagittarius", "pisces"]
    enemy_signs: ["gemini", "virgo"]

houses:
  1:
    name: "Ascendant"
    sanskrit: "Lagna"
    significance: ["self", "personality", "health", "appearance"]
    nature: "angular"
    
  2:
    name: "Wealth"
    sanskrit: "Dhana"
    significance: ["wealth", "family", "speech", "food"]
    nature: "succedent"
    
  3:
    name: "Courage"
    sanskrit: "Parakrama"
    significance: ["siblings", "courage", "communication", "short_journeys"]
    nature: "cadent"

remedies:
  gemstones:
    sun: ["ruby", "red_garnet"]
    moon: ["pearl", "moonstone"]
    mars: ["red_coral", "carnelian"]
    mercury: ["emerald", "green_tourmaline"]
    jupiter: ["yellow_sapphire", "topaz"]
    venus: ["diamond", "white_sapphire"]
    saturn: ["blue_sapphire", "amethyst"]
    rahu: ["hessonite", "gomed"]
    ketu: ["cats_eye", "chrysoberyl"]
    
  colors:
    sun: ["red", "orange", "saffron"]
    moon: ["white", "silver", "cream"]
    mars: ["red", "crimson", "maroon"]
    mercury: ["green", "emerald"]
    jupiter: ["yellow", "golden"]
    venus: ["white", "pink", "light_blue"]
    saturn: ["blue", "black", "dark_colors"]
    
  donations:
    sun: ["wheat", "jaggery", "copper"]
    moon: ["rice", "milk", "silver"]
    mars: ["red_lentils", "jaggery", "copper"]
    mercury: ["green_vegetables", "books"]
    jupiter: ["yellow_items", "turmeric", "gold"]
    venus: ["white_items", "sugar", "silver"]
    saturn: ["black_items", "iron", "oil"]
    
  mantras:
    sun: ["Om Hraam Hreem Hraum Sah Suryaya Namaha", "Gayatri Mantra"]
    moon: ["Om Shraam Shreem Shraum Sah Chandraya Namaha", "Om Namah Shivaya"]
    mars: ["Om Angarakaya Namaha", "Hanuman Chalisa"]
    mercury: ["Om Budhaya Namaha", "Vishnu Sahasranama"]
    jupiter: ["Om Brihaspataye Namaha", "Guru Mantra"]
    venus: ["Om Shukraya Namaha", "Lakshmi Mantra"]
    saturn: ["Om Shanaye Namaha", "Shani Mantra"]

nakshatras:
  ashwini:
    lord: ketu
    deity: ashwini_kumaras
    nature: light
    element: earth
    
  bharani:
    lord: venus
    deity: yama
    nature: fierce
    element: earth
    
  krittika:
    lord: sun
    deity: agni
    nature: mixed
    element: fire
    
  rohini:
    lord: moon
    deity: brahma
    nature: fixed
    element: earth

yogas:
  raj_yogas:
    - name: "Dharma Karmadhipati Yoga"
      description: "Lords of 1st and 9th houses in conjunction or mutual aspect"
      effects: ["success", "recognition", "spiritual_growth"]
      
    - name: "Gaja Kesari Yoga"
      description: "Jupiter and Moon in angular positions from each other"
      effects: ["wisdom", "prosperity", "good_reputation"]

doshas:
  manglik_dosha:
    conditions:
      - mars_in_houses: [1, 2, 4, 7, 8, 12]
      - mars_aspects: ["7th_house_from_mars"]
    remedies:
      - "Donate red lentils on Tuesdays"
      - "Worship Hanuman every Tuesday"
      - "Perform Mangal Shanti Puja"
      
  kaal_sarp_dosha:
    conditions:
      - all_planets_between_rahu_ketu: true
    remedies:
      - "Perform Kaal Sarp Shanti Puja"
      - "Chant Maha Mrityunjaya Mantra"
      - "Visit Shiva temples on Mondays"

lal_kitab_rules:
  general_principles:
    - "Every planet has a friend and enemy house"
    - "Planets give results based on their placement and company"
    - "Simple remedies can neutralize malefic effects"
    - "Donation and charity are powerful remedies"
    
  planet_relationships:
    sun:
      friends: [moon, mars, jupiter]
      enemies: [saturn, venus, rahu, ketu]
      neutral: [mercury]
      
    moon:
      friends: [sun, mercury]
      enemies: [none]
      neutral: [mars, jupiter, venus, saturn, rahu, ketu]
      
    mars:
      friends: [sun, moon, jupiter]
      enemies: [mercury]
      neutral: [venus, saturn, rahu, ketu]
      
  simple_remedies:
    financial_problems:
      - "Keep a piece of silver in wallet"
      - "Donate white items on Mondays"
      - "Feed fish in water bodies"
      - "Respect and serve parents"
      
    health_issues:
      - "Drink water from silver vessel"
      - "Wear copper bracelet"
      - "Donate medicines to poor"
      - "Plant trees and care for them"
      
    relationship_problems:
      - "Donate white flowers on Fridays"
      - "Serve and respect spouse"
      - "Keep fast on Fridays"
      - "Wear white clothes on Fridays"
      
    career_obstacles:
      - "Donate black items on Saturdays"
      - "Serve elderly people"
      - "Keep iron piece in pocket"
      - "Chant Hanuman Chalisa daily"
