
english:
  welcome: "Welcome to Astro AI Companion! ЁЯМЯ"
  registration_start: "Let's create your astrological profile."
  ask_name: "Please enter your full name:"
  ask_dob: "Please enter your date of birth (DD/MM/YYYY):"
  ask_tob: "Please enter your time of birth (HH:MM in 24-hour format):"
  ask_location: "Please enter your birth location (City, Country):"
  profile_created: "Your profile has been created successfully! тЬи"
  daily_greeting: "Good morning! Here's your daily astrological insight:"
  remedies_title: "ЁЯФо Recommended Remedies:"
  master_remedies_title: "тнР Master Remedies (Top 5):"
  feedback_prompt: "Please rate your last prediction (1-10) and add a comment:\n/feedback 8 Very accurate!"
  feedback_thanks: "Thank you! Your feedback helps us improve our predictions. ЁЯМЯ"
  feedback_error: "Please use format: /feedback <rating 1-10> <optional comment>"
  eval_stats_title: "ЁЯУК Prediction Quality Statistics:\n\n"
  stats_error: "Unable to retrieve statistics at this time."
  prediction_quality_low: "тЪая╕П Unable to generate a high-quality prediction at this time. Please try again later."
  help_text: |
    ЁЯМЯ *Astro AI Companion Commands*
    
    ЁЯУЕ *Predictions:*
    /daily - Get today's prediction
    /weekly - Get this week's forecast
    /monthly - Get this month's prediction
    
    ЁЯФо *Remedies & Profile:*
    /remedies - Get current remedies
    /profile - View your profile
    
    тЪЩя╕П *Settings:*
    /language - Change language preference
    
    ЁЯУК *Quality & Feedback:*
    /feedback <rating> <comment> - Rate predictions
    /stats - View prediction quality stats
    
    тЭУ *Help:*
    /help - Show this help message
    
    ЁЯУ▒ You can also use the menu buttons below!
  
marathi:
  welcome: "рдЬреНрдпреЛрддрд┐рд╖ AI рд╕рд╛рдереАрджрд╛рд░рд╛рдордзреНрдпреЗ рдЖрдкрд▓реЗ рд╕реНрд╡рд╛рдЧрдд рдЖрд╣реЗ! ЁЯМЯ"
  registration_start: "рдЪрд▓рд╛ рдЖрдкрд▓реА рдЬреНрдпреЛрддрд┐рд╖реАрдп рдкреНрд░реЛрдлрд╛рдЗрд▓ рддрдпрд╛рд░ рдХрд░реВрдпрд╛."
  ask_name: "рдХреГрдкрдпрд╛ рдЖрдкрд▓реЗ рдкреВрд░реНрдг рдирд╛рд╡ рдЯрд╛рдХрд╛:"
  ask_dob: "рдХреГрдкрдпрд╛ рдЖрдкрд▓реА рдЬрдиреНрдорддрд╛рд░реАрдЦ рдЯрд╛рдХрд╛ (DD/MM/YYYY):"
  ask_tob: "рдХреГрдкрдпрд╛ рдЖрдкрд▓рд╛ рдЬрдиреНрдорд╡реЗрд│ рдЯрд╛рдХрд╛ (HH:MM 24-рддрд╛рд╕ рд╕реНрд╡рд░реВрдкрд╛рдд):"
  ask_location: "рдХреГрдкрдпрд╛ рдЖрдкрд▓реЗ рдЬрдиреНрдорд╕реНрдерд╛рди рдЯрд╛рдХрд╛ (рд╢рд╣рд░, рджреЗрд╢):"
  profile_created: "рдЖрдкрд▓реА рдкреНрд░реЛрдлрд╛рдЗрд▓ рдпрд╢рд╕реНрд╡реАрд░рд┐рддреНрдпрд╛ рддрдпрд╛рд░ рдЭрд╛рд▓реА рдЖрд╣реЗ! тЬи"
  daily_greeting: "рд╕реБрдкреНрд░рднрд╛рдд! рдЖрдЬрдЪрд╛ рдЖрдкрд▓рд╛ рдЬреНрдпреЛрддрд┐рд╖реАрдп рдЕрдВрддрд░реНрджреГрд╖реНрдЯреА:"
  remedies_title: "ЁЯФо рд╢рд┐рдлрд╛рд░рд╕ рдХреЗрд▓реЗрд▓реЗ рдЙрдкрд╛рдп:"
  master_remedies_title: "тнР рдореБрдЦреНрдп рдЙрдкрд╛рдп (рдЯреЙрдк 5):"
  feedback_prompt: "рдХреГрдкрдпрд╛ рдЖрдкрд▓реНрдпрд╛ рд╢реЗрд╡рдЯрдЪреНрдпрд╛ рднрд╡рд┐рд╖реНрдпрд╡рд╛рдгреАрд▓рд╛ рд░реЗрдЯрд┐рдВрдЧ рджреНрдпрд╛ (рез-резреж) рдЖрдгрд┐ рдЯрд┐рдкреНрдкрдгреА рдЬреЛрдбрд╛:\n/feedback 8 рдЕрддреНрдпрдВрдд рдЕрдЪреВрдХ!"
  feedback_thanks: "рдзрдиреНрдпрд╡рд╛рдж! рдЖрдкрд▓рд╛ рдЕрднрд┐рдкреНрд░рд╛рдп рдЖрдореНрд╣рд╛рд▓рд╛ рд╕реБрдзрд╛рд░рдгреНрдпрд╛рд╕ рдорджрдд рдХрд░рддреЛ. ЁЯМЯ"
  feedback_error: "рдХреГрдкрдпрд╛ рд╣реЗ рдлреЙрд░реНрдореЗрдЯ рд╡рд╛рдкрд░рд╛: /feedback <рд░реЗрдЯрд┐рдВрдЧ рез-резреж> <рдРрдЪреНрдЫрд┐рдХ рдЯрд┐рдкреНрдкрдгреА>"
  eval_stats_title: "ЁЯУК рднрд╡рд┐рд╖реНрдпрд╡рд╛рдгреА рдЧреБрдгрд╡рддреНрддрд╛ рдЖрдХрдбреЗрд╡рд╛рд░реА:\n\n"
  stats_error: "рд╕рдзреНрдпрд╛ рдЖрдХрдбреЗрд╡рд╛рд░реА рдорд┐рд│рд╡рдгреНрдпрд╛рдд рдЕрдХреНрд╖рдо."
  prediction_quality_low: "тЪая╕П рд╕рдзреНрдпрд╛ рдЙрдЪреНрдЪ-рдЧреБрдгрд╡рддреНрддреЗрдЪреА рднрд╡рд┐рд╖реНрдпрд╡рд╛рдгреА рддрдпрд╛рд░ рдХрд░рдгреНрдпрд╛рдд рдЕрдХреНрд╖рдо. рдХреГрдкрдпрд╛ рдирдВрддрд░ рдкреБрдиреНрд╣рд╛ рдкреНрд░рдпрддреНрди рдХрд░рд╛."
  help_text: |
    ЁЯМЯ *рдЬреНрдпреЛрддрд┐рд╖ AI рд╕рд╛рдереАрджрд╛рд░ рдЖрджреЗрд╢*
    
    ЁЯУЕ *рднрд╡рд┐рд╖реНрдпрд╡рд╛рдгреА:*
    /daily - рдЖрдЬрдЪреА рднрд╡рд┐рд╖реНрдпрд╡рд╛рдгреА рдорд┐рд│рд╡рд╛
    /weekly - рдпрд╛ рдЖрдард╡рдбреНрдпрд╛рдЪреЗ рдЕрдВрджрд╛рдЬ рдорд┐рд│рд╡рд╛
    /monthly - рдпрд╛ рдорд╣рд┐рдиреНрдпрд╛рдЪреА рднрд╡рд┐рд╖реНрдпрд╡рд╛рдгреА рдорд┐рд│рд╡рд╛
    
    ЁЯФо *рдЙрдкрд╛рдп рдЖрдгрд┐ рдкреНрд░реЛрдлрд╛рдЗрд▓:*
    /remedies - рд╕рдзреНрдпрд╛рдЪреЗ рдЙрдкрд╛рдп рдорд┐рд│рд╡рд╛
    /profile - рдЖрдкрд▓реА рдкреНрд░реЛрдлрд╛рдЗрд▓ рдкрд╣рд╛
    
    тЪЩя╕П *рд╕реЗрдЯрд┐рдВрдЧреНрдЬ:*
    /language - рднрд╛рд╖рд╛ рдкреНрд░рд╛рдзрд╛рдиреНрдп рдмрджрд▓рд╛
    
    ЁЯУК *рдЧреБрдгрд╡рддреНрддрд╛ рдЖрдгрд┐ рдЕрднрд┐рдкреНрд░рд╛рдп:*
    /feedback <рд░реЗрдЯрд┐рдВрдЧ> <рдЯрд┐рдкреНрдкрдгреА> - рднрд╡рд┐рд╖реНрдпрд╡рд╛рдгреАрд▓рд╛ рд░реЗрдЯрд┐рдВрдЧ рджреНрдпрд╛
    /stats - рднрд╡рд┐рд╖реНрдпрд╡рд╛рдгреА рдЧреБрдгрд╡рддреНрддрд╛ рдЖрдХрдбреЗрд╡рд╛рд░реА рдкрд╣рд╛
    
    тЭУ *рдорджрдд:*
    /help - рд╣рд╛ рдорджрдд рд╕рдВрджреЗрд╢ рджрд╛рдЦрд╡рд╛
    
    ЁЯУ▒ рдЖрдкрдг рдЦрд╛рд▓реАрд▓ рдореЗрдиреВ рдмрдЯрди рджреЗрдЦреАрд▓ рд╡рд╛рдкрд░реВ рд╢рдХрддрд╛!

prediction_types:
  english:
    daily: "Daily Prediction"
    weekly: "Weekly Forecast"
    monthly: "Monthly Overview"
    quarterly: "Quarterly Insights"
    annual: "Annual Forecast"
    
  marathi:
    daily: "рджреИрдирд┐рдХ рднрд╡рд┐рд╖реНрдпрд╡рд╛рдгреА"
    weekly: "рд╕рд╛рдкреНрддрд╛рд╣рд┐рдХ рдЕрдВрджрд╛рдЬ"
    monthly: "рдорд╛рд╕рд┐рдХ рд╡рд┐рд╣рдВрдЧрд╛рд╡рд▓реЛрдХрди"
    quarterly: "рддреНрд░реИрдорд╛рд╕рд┐рдХ рдЕрдВрддрд░реНрджреГрд╖реНрдЯреА"
    annual: "рд╡рд╛рд░реНрд╖рд┐рдХ рдЕрдВрджрд╛рдЬ"

remedy_categories:
  english:
    gemstone: "Gemstone"
    color: "Favorable Colors"
    donation: "Charitable Donations"
    mantra: "Sacred Mantras"
    food: "Dietary Recommendations"
    
  marathi:
    gemstone: "рд░рддреНрди"
    color: "рдЕрдиреБрдХреВрд▓ рд░рдВрдЧ"
    donation: "рджрд╛рдирдзрд░реНрдо"
    mantra: "рдкрд╡рд┐рддреНрд░ рдордВрддреНрд░"
    food: "рдЖрд╣рд╛рд░рд╡рд┐рд╖рдпрдХ рд╢рд┐рдлрд╛рд░рд╕реА"
